CREATE DATABASE IF NOT EXISTS restaurant_db;
USE restaurant_db;

CREATE TABLE IF NOT EXISTS menu (
  id INT AUTO_INCREMENT PRIMARY KEY,
  branch INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100),
  portion VARCHAR(100),
  price INT NOT NULL,
  serves INT NOT NULL DEFAULT 1
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  branch INT NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  order_date DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- Sample Menu Data for Branch 1,2,3
INSERT INTO menu (branch, name, category, portion, price, serves) VALUES
(1, 'Cheeseburger', 'Burger', 'Single', 120, 1),
(1, 'Veggie Burger', 'Burger', 'Single', 100, 1),
(1, 'Chicken Sandwich', 'Sandwich', 'Regular', 110, 1),
(1, 'French Fries', 'Sides', 'Medium', 50, 1),
(1, 'Onion Rings', 'Sides', 'Small', 40, 1),
(1, 'Coke', 'Beverage', '500ml', 30, 1),
(1, 'Pepsi', 'Beverage', '500ml', 30, 1),
(2, 'Margherita Pizza', 'Pizza', 'Medium', 200, 2),
(2, 'Pepperoni Pizza', 'Pizza', 'Large', 300, 3),
(2, 'Veggie Pizza', 'Pizza', 'Medium', 220, 2),
(2, 'Chicken Wings', 'Appetizer', '6 pcs', 150, 1),
(2, 'Garlic Bread', 'Appetizer', '4 pcs', 70, 1),
(2, 'Lemonade', 'Beverage', '300ml', 35, 1),
(2, 'Iced Tea', 'Beverage', '300ml', 35, 1),
(3, 'Pasta Alfredo', 'Pasta', 'Regular', 180, 1),
(3, 'Pasta Bolognese', 'Pasta', 'Regular', 190, 1),
(3, 'Spaghetti Carbonara', 'Pasta', 'Regular', 200, 1),
(3, 'Caesar Salad', 'Salad', 'Large', 150, 1),
(3, 'Greek Salad', 'Salad', 'Medium', 130, 1),
(3, 'Water', 'Beverage', '500ml', 20, 1),
(1, 'Chocolate Cake', 'Dessert', 'Slice', 80, 1),
(1, 'Ice Cream', 'Dessert', 'Single Scoop', 60, 1),
(2, 'Brownie', 'Dessert', 'Single', 70, 1),
(2, 'Cheesecake', 'Dessert', 'Slice', 90, 1),
(3, 'Smoothie', 'Beverage', '300ml', 60, 1),
(3, 'Fruit Juice', 'Beverage', '300ml', 50, 1),
(1, 'Chicken Nuggets', 'Sides', '6 pcs', 70, 1),
(2, 'Mozzarella Sticks', 'Sides', '6 pcs', 80, 1),
(3, 'Tiramisu', 'Dessert', 'Slice', 100, 1),
(3, 'Garlic Pasta', 'Pasta', 'Regular', 170, 1);
(1, 'Grilled Chicken', 'Main', 'Regular', 220, 1),
(1, 'Beef Steak', 'Main', 'Large', 350, 2),
(1, 'Veg Sandwich', 'Sandwich', 'Regular', 90, 1),
(1, 'Mashed Potato', 'Sides', 'Medium', 60, 1),
(1, 'Coleslaw', 'Salad', 'Small', 40, 1),
(1, 'Milkshake', 'Beverage', '300ml', 50, 1),
(1, 'Hot Chocolate', 'Beverage', '250ml', 45, 1),
(2, 'BBQ Chicken Pizza', 'Pizza', 'Large', 320, 3),
(2, 'Hawaiian Pizza', 'Pizza', 'Medium', 280, 2),
(2, 'Veggie Delight Pizza', 'Pizza', 'Small', 180, 1),
(2, 'Buffalo Wings', 'Appetizer', '8 pcs', 180, 1),
(2, 'Stuffed Mushrooms', 'Appetizer', '6 pcs', 100, 1),
(2, 'Orange Juice', 'Beverage', '300ml', 40, 1),
(2, 'Green Tea', 'Beverage', '250ml', 35, 1),
(3, 'Fettuccine Alfredo', 'Pasta', 'Regular', 190, 1),
(3, 'Lasagna', 'Pasta', 'Regular', 210, 1),
(3, 'Spaghetti Napoli', 'Pasta', 'Regular', 180, 1),
(3, 'Greek Yogurt Salad', 'Salad', 'Medium', 120, 1),
(3, 'Caprese Salad', 'Salad', 'Medium', 140, 1),
(3, 'Sparkling Water', 'Beverage', '500ml', 25, 1),
(1, 'Brownie Sundae', 'Dessert', 'Single', 85, 1),
(1, 'Fruit Tart', 'Dessert', 'Slice', 75, 1),
(2, 'Chocolate Mousse', 'Dessert', 'Cup', 80, 1),
(2, 'Apple Pie', 'Dessert', 'Slice', 70, 1),
(3, 'Berry Smoothie', 'Beverage', '300ml', 65, 1),
(3, 'Pineapple Juice', 'Beverage', '300ml', 55, 1),
(1, 'Fish Fingers', 'Sides', '6 pcs', 90, 1),
(2, 'Cheese Balls', 'Sides', '6 pcs', 85, 1),
(3, 'Chocolate Lava Cake', 'Dessert', 'Slice', 110, 1),
(3, 'Pesto Pasta', 'Pasta', 'Regular', 175, 1);
(1, 'Grilled Veggie Wrap', 'Sandwich', 'Regular', 95, 1),
(1, 'Chicken Wrap', 'Sandwich', 'Regular', 120, 1),
(1, 'Loaded Nachos', 'Appetizer', 'Large', 150, 2),
(1, 'Cheese Fries', 'Sides', 'Medium', 65, 1),
(1, 'Mozzarella Pizza Slice', 'Pizza', 'Single', 80, 1),
(1, 'Strawberry Milkshake', 'Beverage', '300ml', 55, 1),
(1, 'Vanilla Milkshake', 'Beverage', '300ml', 50, 1),
(2, 'Chicken BBQ Pizza', 'Pizza', 'Medium', 290, 2),
(2, 'Four Cheese Pizza', 'Pizza', 'Large', 320, 3),
(2, 'Veggie Supreme Pizza', 'Pizza', 'Medium', 250, 2),
(2, 'Potato Wedges', 'Sides', 'Medium', 60, 1),
(2, 'Chicken Tenders', 'Sides', '6 pcs', 140, 1),
(2, 'Mango Juice', 'Beverage', '300ml', 45, 1),
(2, 'Cappuccino', 'Beverage', '250ml', 60, 1),
(3, 'Ravioli', 'Pasta', 'Regular', 200, 1),
(3, 'Mac and Cheese', 'Pasta', 'Regular', 180, 1),
(3, 'Spinach Alfredo Pasta', 'Pasta', 'Regular', 190, 1),
(3, 'Mixed Green Salad', 'Salad', 'Medium', 130, 1),
(3, 'Caesar Chicken Salad', 'Salad', 'Large', 160, 1),
(3, 'Herbal Tea', 'Beverage', '250ml', 30, 1),
(1, 'Cupcake', 'Dessert', 'Single', 50, 1),
(1, 'Carrot Cake', 'Dessert', 'Slice', 80, 1),
(2, 'Lemon Tart', 'Dessert', 'Slice', 75, 1),
(2, 'Panna Cotta', 'Dessert', 'Cup', 85, 1),
(3, 'Banana Smoothie', 'Beverage', '300ml', 60, 1),
(3, 'Orange Smoothie', 'Beverage', '300ml', 60, 1),
(1, 'Veg Spring Rolls', 'Appetizer', '4 pcs', 70, 1),
(2, 'Chicken Spring Rolls', 'Appetizer', '4 pcs', 90, 1),
(3, 'Chocolate Brownie', 'Dessert', 'Slice', 95, 1),
(3, 'Spaghetti Pesto', 'Pasta', 'Regular', 180, 1);
(1, 'Buffalo Chicken Wrap', 'Sandwich', 'Regular', 130, 1),
(1, 'Veggie Quesadilla', 'Sandwich', 'Regular', 110, 1),
(1, 'Cheese Nachos', 'Appetizer', 'Large', 140, 2),
(1, 'Potato Skins', 'Sides', '6 pcs', 75, 1),
(1, 'Mini Margherita Pizza', 'Pizza', 'Single', 90, 1),
(1, 'Oreo Milkshake', 'Beverage', '300ml', 60, 1),
(1, 'Strawberry Smoothie', 'Beverage', '300ml', 55, 1),
(2, 'Pepperoni Feast Pizza', 'Pizza', 'Large', 330, 3),
(2, 'Veggie Fiesta Pizza', 'Pizza', 'Medium', 260, 2),
(2, 'Chicken Supreme Pizza', 'Pizza', 'Medium', 310, 2),
(2, 'Onion Rings Basket', 'Sides', 'Large', 80, 1),
(2, 'Buffalo Chicken Wings', 'Appetizer', '8 pcs', 190, 1),
(2, 'Pineapple Smoothie', 'Beverage', '300ml', 55, 1),
(2, 'Iced Latte', 'Beverage', '250ml', 60, 1),
(3, 'Fettuccine Pesto', 'Pasta', 'Regular', 185, 1),
(3, 'Macaroni Bolognese', 'Pasta', 'Regular', 190, 1),
(3, 'Cheese Ravioli', 'Pasta', 'Regular', 200, 1),
(3, 'Quinoa Salad', 'Salad', 'Medium', 140, 1),
(3, 'Chicken Caesar Salad', 'Salad', 'Large', 170, 1),
(3, 'Chamomile Tea', 'Beverage', '250ml', 30, 1),
(1, 'Chocolate Muffin', 'Dessert', 'Single', 55, 1),
(1, 'Strawberry Tart', 'Dessert', 'Slice', 75, 1),
(2, 'Chocolate Cupcake', 'Dessert', 'Single', 60, 1),
(2, 'Vanilla Pudding', 'Dessert', 'Cup', 70, 1),
(3, 'Mango Smoothie', 'Beverage', '300ml', 60, 1),
(3, 'Berry Juice', 'Beverage', '300ml', 55, 1),
(1, 'Veggie Spring Rolls', 'Appetizer', '4 pcs', 65, 1),
(2, 'Chicken Fingers', 'Appetizer', '6 pcs', 120, 1),
(3, 'Chocolate Cheesecake', 'Dessert', 'Slice', 100, 1),
(3, 'Spaghetti Alfredo', 'Pasta', 'Regular', 190, 1);

-- Sample Orders for Branch 1
INSERT INTO orders (branch, item_name) VALUES
(1, 'Cheeseburger'),
(1, 'Mini Margherita Pizza'),
(1, 'BBQ Chicken Pizza'),
(1, 'Veggie Burger'),
(1, 'Chicken Sandwich'),
(1, 'French Fries'),
(1, 'Coke'),
(1, 'Chocolate Cake'),
(1, 'Ice Cream'),
(1, 'Grilled Chicken'),
(1, 'Beef Steak'),
(1, 'Chicken Wrap'),
(1, 'Loaded Nachos'),
(1, 'Caesar Salad'),
(1, 'Chocolate Cheesecake'),
(2, 'Pepperoni Pizza'),
(2, 'Veggie Pizza'),
(2, 'Chicken Wings'),
(2, 'Garlic Bread'),
(2, 'Lemonade'),
(2, 'Brownie'),
(2, 'Cheesecake'),
(2, 'Mozzarella Sticks'),
(2, 'Buffalo Chicken Pizza'),
(2, 'Four Cheese Pizza'),
(2, 'Chicken Supreme Pizza'),
(3, 'Pasta Alfredo'),
(3, 'Pasta Bolognese'),
(3, 'Spaghetti Carbonara'),
(3, 'Greek Salad'),
(3, 'Tiramisu'),
(3, 'Berry Smoothie');
